services:
  # Svelte Frontend
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
    container_name: lvhf
    restart: unless-stopped
    ports:
      - '5174:5174'
    volumes:
      # Prevent overwriting node_modules
      - /app/node_modules
